# Generated by Django 4.2.7 on 2025-08-19 04:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_cart_order_payment_status_cartitem'),
        ('products', '0013_add_independent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code that customers will use', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the coupon offer', null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount for percentage discounts', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required to use this coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField(help_text='Coupon validity start date and time')),
                ('valid_to', models.DateTimeField(help_text='Coupon validity end date and time')),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, help_text='Total number of times this coupon can be used (null for unlimited)', null=True)),
                ('usage_limit_per_customer', models.PositiveIntegerField(default=1, help_text='Number of times a single customer can use this coupon')),
                ('applicable_to', models.CharField(choices=[('all', 'All Products'), ('specific_products', 'Specific Products'), ('specific_categories', 'Specific Categories')], default='all', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the coupon is currently active')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Categories this coupon applies to (if applicable_to is SPECIFIC_CATEGORIES)', related_name='applicable_coupons', to='products.category')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Products this coupon applies to (if applicable_to is SPECIFIC_PRODUCTS)', related_name='applicable_coupons', to='products.product')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Actual discount amount applied', max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='coupons.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='orders.order')),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage History',
                'verbose_name_plural': 'Coupon Usage History',
                'db_table': 'coupon_usage_history',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_code_94ae53_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_to'], name='coupons_valid_f_8ea39f_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active'], name='coupons_is_acti_dbb3f6_idx'),
        ),
    ]
