# Generated by Django 5.2.5 on 2025-08-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_categories',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_products',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_to',
        ),
    ]
