# Generated by Django 5.2.5 on 2025-08-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='holister_points',
            field=models.PositiveIntegerField(default=100, help_text="User's loyalty points"),
        ),
    ]
