# Generated by Django 4.2.7 on 2025-08-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('CAD', 'CAD (C$)'), ('AUD', 'AUD (A$)'), ('JPY', 'JPY (¥)')], default='USD', max_length=3, verbose_name='Currency')),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('EST', 'Eastern Standard Time'), ('PST', 'Pacific Standard Time'), ('CST', 'Central Standard Time'), ('MST', 'Mountain Standard Time'), ('GMT', 'Greenwich Mean Time'), ('CET', 'Central European Time'), ('IST', 'Indian Standard Time'), ('JST', 'Japan Standard Time'), ('AEST', 'Australian Eastern Standard Time')], default='UTC', max_length=10, verbose_name='Timezone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
