# Generated by Django 4.2.7 on 2025-08-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_terms_and_conditions_privacy_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('google_pay', 'Google Pay'), ('apple_pay', 'Apple Pay')], max_length=20, unique=True, verbose_name='Payment Provider')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox/Test'), ('production', 'Production')], default='sandbox', max_length=20, verbose_name='Environment')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('api_key', models.TextField(blank=True, verbose_name='API Key')),
                ('secret_key', models.TextField(blank=True, verbose_name='Secret Key')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Additional Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['provider'],
            },
        ),
    ]
