# Generated by Django 4.2.7 on 2025-08-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_revert_category_to_charfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='category',
            table='product_categories',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
