# Generated by Django 4.2.7 on 2025-08-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_independent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="Size value (e.g., 'S', 'M', 'L', '42', '10')", max_length=20)),
                ('display_name', models.CharField(help_text='Display name for the size', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order within category (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.category')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ['category', 'order', 'value'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
