# Generated by Django 4.2.7 on 2025-08-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_add_size_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image', null=True, upload_to='category_images/'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
